version: '3'

services:
  db:
   image: postgres:14.3
   restart: always
   ports:
     - "5432:5432"
   environment:
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_USER: ${POSTGRES_USER}
   #container_name: prueba
   volumes:
     - ./postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=carlos@mail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - '5050:80'
    depends_on:
      - db
